### ISSUE TITLE
Calibrate the Razor IMU

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/IGVC-2017#110]
We've just received our brand spanking new IMU! It's pretty cool, lots of pretty accurate data, and all in a neat little package. However, it still needs to be calibrated. Calibration instructions can be found [here](http://wiki.ros.org/razor_imu_9dof) (under the `indigo` section). The determined values should be written to our copy of the firmware file in `src/firmware/razor_imu_9dof`, as per the calibration instructions.

**Comment by raadkhan** [comment]
Got it 👍

**Comment by garethellis0** [comment]
@raadkhan - just a quick note that this is on hold until I merge the gps_driver code (currently no PR open yet), as I moved the location of the firmware code on the same branch

**Comment by garethellis0** [comment]
@raadkhan - just put it on it's own branch and open a PR for it, I can merge it to master and then merge master back into  other branches if I need it

**Comment by garethellis0** [comment]
Closed via #118
