### ISSUE TITLE
Test (and hopefully fix) the compass on the razor imu

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/IGVC-2017#142]
- Currently, the orientation data we're getting from the razor IMU is basically useless. It doesn't seem to be pointing in the right direction, and will not change even **remotely** the right amount when rotated.
- I suspect that this is due to the compass being either broken, or completely miscalibrated

**TODO:**
- Test the razor IMU in several different environments to ensure that the bad behavior is not just being caused by things in the local environment, just as large chunks of metal
- Attempt to fix it. A good starting point for this would be to properly calibrate it [here](https://github.com/KristofRobot/razor_imu_9dof#calibrate).

**Comment by raadkhan** [comment]
- accelerometer and gyroscope calibrated
- magnetometer on hold

**Comment by garethellis0** [comment]
We have a new IMU, and will not be using the razor this year, so this is no longer relevant.
