### ISSUE TITLE
Create a node which transforms Gazebo's Zed point cloud output internally

### ISSUE THREAD

**Issue by ValRat** [UBC-Snowbots/IGVC-2017#170]
Currently, we specify a transform in `jfrost.xacro` in order to re-orient the output of the "Zed" module of the jfrost simulation to the proper place in the world. But this means that intermediate nodes which accesses this data *cough* `zed_filter` *cough* uses the old pre-transformed point-cloud data which results in wonky and incorrect data output.

We should consider writing a node which transforms the Zed's point cloud output internally so that all data which depends on it are using correct world-frame coordinates. See `jfrost.xacro` for the specific transform hack.

**Comment by garethellis0** [comment]
closed by #175
