### ISSUE TITLE
Come up with a better dangerScore function for LidarObstacle

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/IGVC-2017#68]
- Currently is just `sin(the angle of the obstacle relative to the robot) * (1/the distance of the obstacle from the robot)`
- is in `src/decision/LidarObstacle.cpp`

**Comment by garethellis0** [comment]
@raadkhan - Just to reiterate over what we talked about today:

- Figure out a better function for determining the danger score of a given obstacle in `src/decision/LidarObstacle.cpp`
- Write some tests for it in `src/decision/test/lidar-decision-test.cpp`, following the tests that are already there as guides
- Make sure your code compiles and your tests run
- Commit your code and open up a new pull request, then add Val and I as reviewers

Also, great work with the IMU today! :smile:

**Comment by raadkhan** [comment]
Alright 🤔 sounds like a plan.

Again thanks for the help Gareth, you're the man

**Comment by raadkhan** [comment]
@garethellis0, what exactly does `sin(the angle of the obstacle relative to the robot) * (1/the distance of the obstacle from the robot)` return? What does it mean mathematically?

**Comment by garethellis0** [comment]
@raadkhan - the most dangerous obstacles are the ones right in front of us, and close to use. So I just kinda choose something that gave a lower score to objects farther away (`1/the distance of the obstacle from the robot`) and a lower score to obstacles that are not directly in front of us (`sin(the angle to the obstacle)` will yield a lower score with a greater absolute angle -  keep in mind that directly in front of the robot is 0 degrees)

**Comment by garethellis0** [comment]
Just for future reference, if you put something like "closes #35" in your PR message, Github will automatically close the issue when your PR has been merged. (https://help.github.com/articles/closing-issues-via-commit-messages/) (I only discovered this a few weeks ago)

**Comment by garethellis0** [comment]
closed via #112
