### ISSUE TITLE
Calibrate the ZED Camera

### ISSUE THREAD

**Issue by ValRat** [UBC-Snowbots/IGVC-2017#87]
On initialise (of the sample programs) the ZED looks for a calibration file online but it can't download it through the terminal. Going to the link it [provides](http://calib.stereolab.com/?SN=12176), the file can be downloaded through a browser. Maybe try to figure out why it can't get the files through the terminal.
But we can download the file and set the calibration manually for a simple fix.

**Comment by garethellis0** [comment]
@ValRat - did we resolve this with #98 ?

**Comment by garethellis0** [comment]
@ValRat ^^^^

**Comment by ValRat** [comment]
Oops, yeah.

**Comment by garethellis0** [comment]
:+1:
