### ISSUE TITLE
Add mapping package to setup script 

### ISSUE THREAD

**Issue by ValRat** [UBC-Snowbots/IGVC-2017#93]
Just a reminder to do this sometime in the future:
Add the package dependency `ros-kinetic-grid-map && laser_geometry` to both the setup script and the CI script if applicable so that project compiles for everyone once #52 gets merged in.

**Comment by garethellis0** [comment]
Adding this to the setup script should be easy, just add it to `install_dependencies`. CI actually (should) do all the dependencies just based off the CMake files (testing needed)

**Comment by ValRat** [comment]
Seems like all you gotta do is put them as dependencies under package.xml :+1:

**Comment by garethellis0** [comment]
Sweet! :smiley:
